#NamedGeneRankList2GseaTable

#Description
#This function takes a named ranked list of genes and applies the fgseaMultilevel function from the fgsea package using multiple gene sets relevant to immunology and blood transcriptomics.

#Usage
#NamedGeneRankList2GseaTable <- function(rankedgenes, geneset = c("all", "bloodmodules", "MSigDB"), output_directory = getwd(), filename_prefix = "myFile", fixed_seed = TRUE, ...)

#Arguments
#rankedgenes          A named vector of a ranking metric such as log2 fold-change with names being HUGO gene symbols. Can also be two column dataframe or tibble where the first column has gene names and the second column is the ranking metric. Vector automatically gets sorted in descending order of ranking metric.
#geneset              Can be "bloodmodules" which includes low- and high-annotation blood transcription modules (Li et al. Nat Immunol 2014 [PMID 24336226]; Kazmin et al PNAS 2017 [PMID 28193898]); Monaco modules (Monaco et al. Cell Reports 2019 [PMID 30726743]); and BloodGen3Modules (Rinchai et al. Binformatics 2021 [PMID 33624743] or "MSigDB" which includes most collections from the Molecular Signature Database v7.4 (https://www.gsea-msigdb.org/gsea/msigdb/) or "all" which includes both.  
#output_directory     User-defined directory path
#filename_prefix      User-defined pre-fix for filename where results will be saved, defaults to "myFile"
#fixed_seed           If TRUE, a fixed seed will be set for reproducibility of exact NES and significance values.
# ...                 All other arguments passed onto fgseaMultilevel

#Value
#Output is a single table of all gene sets. Columns are module_type (e.g. "highBTMs" or "MonacoModules") followed all the columns in the table generated by fgseaMultilevel (see "Value" in fgseaMultilevel help) 


NamedGeneRankList2GseaTable <- function(rankedgenes, geneset = c("all", "bloodmodules", "MSigDB"), output_directory = getwd(), filename_prefix = "myFile", fixed_seed = TRUE, ...) {
  
  library(tidyverse)
  library(fgsea)
  library(data.table)
  library(curl)
  
  if(fixed_seed == TRUE){
    set.seed(12345)
  }
  if(class(rankedgenes) == "data.frame" | class(rankedgenes) == "tbl" | class(rankedgenes) == "data.table"){
    rankedgenes <- deframe(rankedgenes)
  } 
  rankedgenes <- sort(rankedgenes, decreasing = TRUE)
  #for rank lists  that still have original "MARCH" or "SEPT" gene names, replace with "MARCHF" or "SEPTIN"
  if(length(names(rankedgenes)[grepl("MARCHF", names(rankedgenes))]) == 0){
    names(rankedgenes) <- gsub("MARCH", "MARCHF", names(rankedgenes))
    }
  if(length(names(rankedgenes)[grepl("SEPTIN", names(rankedgenes))]) == 0){
    names(rankedgenes) <- gsub("SEPT", "SEPTIN", names(rankedgenes))
    }
  #Load the pathways into a named list
  if(geneset == "all"){
    allGeneSets <- c("MonacoModules", "highBTMs", "lowBTMs", "BloodGen3Module",
                     "MSigDB_Hallmark_v7.4", "MSigDB_C2_biocarta_v7.4", "MSigDB_C2_kegg_v7.4", "MSigDB_C8_all_v7.4","MSigDB_C7_all_v7.4","MSigDB_C5_GO_bp_v7.4", "MSigDB_C5_GO_mf_v7.4")
    }
  if(geneset == "bloodmodules"){
    allGeneSets <- c("MonacoModules", "highBTMs", "lowBTMs", "BloodGen3Module")
    }
  if(geneset == "MSigDB"){
    allGeneSets <- c("MSigDB_Hallmark_v7.4", "MSigDB_C2_biocarta_v7.4", "MSigDB_C2_kegg_v7.4", "MSigDB_C8_all_v7.4","MSigDB_C7_all_v7.4","MSigDB_C5_GO_bp_v7.4", "MSigDB_C5_GO_mf_v7.4")
                     }
  if(!geneset %in% c("all", "bloodmodules", "MSigDB")){
    print("geneset argument can only be 'all', 'bloodmodules', or 'MSigDB'")
    stop()
    }
  myModuleList <- fgseaRes <- c()
  for(i in allGeneSets){
    temp <- tempfile(fileext = ".rds")
    url <- paste0("https://github.com/TranLab/ModuleLists/blob/main/", i, ".rds?raw=true")
    myModuleList[[i]] <- readRDS(url(url, method="libcurl"))
    #for module lists that still have original "MARCH" or "SEPT" gene names, replace with "MARCHF" or "SEPTIN"
    if(length(unlist(myModuleList[[i]])[grepl("MARCHF", unlist(myModuleList[[i]]))]) == 0){
      for(j in 1:length(myModuleList[[i]])){
        myModuleList[[i]][[j]] <- gsub("MARCH", "MARCHF", myModuleList[[i]][[j]])
      }
      }
    if(length(unlist(myModuleList[[i]])[grepl("SEPTIN", unlist(myModuleList[[i]]))]) == 0){
      for(j in 1:length(myModuleList[[i]])){
        myModuleList[[i]][[j]] <- gsub("SEPT", "SEPTIN", myModuleList[[i]][[j]])
      }
      }
    print(paste0("Running fgsea for ", i, " signatures"))
    #for info on the SampleSize argument: https://www.biostars.org/p/479821/
    #run fgsea with 1000 permutations
    
    fgseaRes[[i]] <- fgseaMultilevel(pathways=myModuleList[[i]], stats=rankedgenes, eps = 0, ...) %>%
      as_tibble() %>%
      arrange(desc(NES)) %>% 
      dplyr::select(pathway, ES, NES, size, leadingEdge, pval, padj) %>% 
      mutate(leadingEdge = gsub("^c\\(|\\)$", "", leadingEdge)) %>%
      mutate(leadingEdge = gsub('"', "", leadingEdge)) %>%
      arrange(padj) %>%
      as.data.frame()
    }
  GSEAtab <- fgseaRes %>%
    dplyr::bind_rows(.id = "module_type")
  writexl::write_xlsx(GSEAtab, paste0(output_directory, filename_prefix, " GSEA results ", geneset, ".xlsx"))
  return(GSEAtab)
  close(url)
  }
